### ISSUE TITLE
Documentation for m_cmdFlags from SCmdEvent

### ISSUE THREAD

**Issue by ZephyrBlu** [Blizzard/s2protocol#105]
After browsing through scelight (@icza's implementation of s2protocol) I noticed these flags that are missing from s2protocol. The flags themselves exist in s2protocol, but there's no documentation or hint at what they represent.

Can anyone confirm the flags in scelight are accurate or point me to some documentation around them?

Flags in scelight: https://github.com/icza/scelight/blob/c7c959ca5fc94d9dac57d61ff765c11face12c5a/src-ext-mod-api/hu/scelightapi/sc2/rep/model/gameevents/cmd/ICmdFlag.java

Relevant code in s2protocol: https://github.com/Blizzard/s2protocol/blob/ea1fe843b46ee5589a86054361d8d13e49483790/s2protocol/versions/protocol77661.py#L403-L439

Line 424 reads bits and creates the event which contains `m_cmdFlags` and other information.

`m_cmdFlags` is returned as an integer, which I assume is the integer representation of the flags detailed in scelight.

**Comment by Talv** [comment]
Yes, `m_cmdFlags` is a bitmask type. Available flags are listed in `mods/core.sc2mod/base.sc2data/TriggerLibs/GameData/Unit.galaxy`, which can be extracted from game files. Relevant part: https://github.com/SC2Mapster/SC2GameData/blob/afaee5428f1a40cf80d49d1fc0031b214cb278f7/mods/core.sc2mod/base.sc2data/TriggerLibs/GameData/Unit.galaxy#L291-L317 .
I believe they're mostly self explanatory, but further documentation can be found in SC2Editor, or here: https://mapster.talv.space/galaxy/reference/preset-order-flag (this page was auto-generated from SC2Editor related files).

**Comment by ZephyrBlu** [comment]
Awesome, thanks for the links. It's exactly what I was looking for.
