### ISSUE TITLE
No module named 'protocol80188' - Unpacking replay failed.

### ISSUE THREAD

**Issue by Kaszanas** [Blizzard/s2protocol#111]
While testing replay parsing with s2protocol according to the documentation (https://github.com/Blizzard/s2protocol/blob/master/docs/tutorial_API.rst) using the following code:

```
import s2protocol
import logging
import mpyq
from s2protocol import versions
from settings import LOGGING_FORMAT

logging.basicConfig(level=logging.DEBUG, format=LOGGING_FORMAT)
archive = mpyq.MPQArchive('MyLegitPathToReplay')

contents = archive.header['user_data_header']['content']
logging.info(contents)

header = versions.latest().decode_replay_header(contents)
logging.info(header)

base_build = header['m_version']['m_baseBuild']
logging.info(base_build)

protocol = versions.build(base_build)
```

I was met with following error:
```
Exception has occurred: ImportError
No module named 'protocol80188'
  File "D:\Projects\SC2\testing_s2protocol.py", line 19, in <module>
    protocol = versions.build(base_build)
```

If anyone is willing to provide more information as to how to resolve the following problem I would appreciate that greatly.

**Comment by amartin916** [comment]
Copy and past the previous protocol file and rename it to protocol80188 and you will be good to go

**Comment by Kaszanas** [comment]
@amartin916 Thank You very much for such a quick response this seems to be connected with issue: #110 
Are You sure that nothing changed internally between those versions?
It might be a good idea to introduce a Pull Request for that.

I will try this solution and inform You about the progress

**Comment by amartin916** [comment]
they wouldn't accept the pull request, its an semi automated job that adds the protocol files and the next time they run it, it will be added. I don't ever poke my contacts at blizzards for protocol files that are duplicates of the previous version. And yes I'm 99.99% sure its a duplicate of the previous version, I have processed ~200k replays from this patch with no issues reported to me.

**Comment by Kaszanas** [comment]
Thank You very much for the assistance @amartin916 :)
Indeed it seems to be working correctly at this point.
I am closing this issue.
