### ISSUE TITLE
Morphing an Archon from darktemplar does not have an NNet.Replay.Tracker.SUnitTypeChangeEvent 

### ISSUE THREAD

**Issue by breath20** [Blizzard/s2protocol#12]
I would have expect there to be an event for for the darktemplar changing types into a Archon. 

I see an NNet.Replay.Tracker.SUnitInitEvent for when the Archon was created, but i'm not seeing the  NNet.Replay.Tracker.SUnitTypeChangeEvent for the Dark Templar

**Comment by jrepp** [comment]
I'm going to close this as there is no follow up items.. Just for fun I attached a very small tracker json that demonstrates the events that lead to the birth of a new Archon :)

[archon.zip](https://github.com/Blizzard/s2protocol/files/1089735/archon.zip)
