### ISSUE TITLE
Heroes of the Storm events

### ISSUE THREAD

**Issue by Mischanix** [Blizzard/s2protocol#23]
Are there plans to add Heroes of the Storm events to this or to a new repo?

If there are no plans, can we at least get the debug bytecode for the protocol so that we can format the structs ourselves?  As an example of "debug bytecode", here's the bnet protocol visible in a WoD Debug build:  https://gist.github.com/Mischanix/8776b09b3489a6234ff4

**Comment by crorella** [comment]
+1

**Comment by gman-php** [comment]
Would also love to see the HotS protocols! Would make a lot of things easier!

**Comment by barrett777** [comment]
+1 :)

**Comment by JeremyHutchings** [comment]
+1 :)

**Comment by Mischanix** [comment]
More or less fixed by 970dff
