### ISSUE TITLE
Export LotV Game Balance Data

### ISSUE THREAD

**Issue by icza** [Blizzard/s2protocol#28]
It's great that you added protocol support for LotV beta replays. Thanks for that.

However many of the data extracted from replays with s2protocol is only meaningful with the balance data that can be exported from the map editor (Starcraft II Editor), as File -> Export Balance Data.

Unfortunately this can only be done for Wings of Liberty and Heart of the Swarm expansions. And the LotV beta installation does not include a map editor.

When can we expect Balance Data Export to be available for LotV?

Thanks.

**Comment by dsjoerg** [comment]
+1 from ggtracker.     our users are increasingly asking for LotV support and this would help make it possible.

**Comment by icza** [comment]
LotV is released, and balance data export is available for LotV. Closing the issue.
