### ISSUE TITLE
protocol37117.py

### ISSUE THREAD

**Issue by JeremyHutchings** [Blizzard/s2protocol#29]
Hi there, 

Any plans to add a new file for the latest update ?

Looks like it's a fairly minor change : https://github.com/barrett777/Heroes.ReplayParser/commit/2582e1fcb687da30d6823ccc25441e000b607ab9

Thanks :)

**Comment by jrepp** [comment]
We should be getting regular updates from our build server. Heroes and SC2 have different branches in code and different builds / protocols. For the hero protocol go to https://github.com/Blizzard/heroprotocol.
