### ISSUE TITLE
protocol file missing for base build 42253

### ISSUE THREAD

**Issue by gman-php** [Blizzard/s2protocol#33]
Hey there,

any plans to add the protocol file for this update?

Thanks and greetings,

Andy!

**Comment by koalaling** [comment]
Hey thanks for the report. We've sorted through a glitch in our new automated s2protocol upload, should be good to go!

**Comment by dsjoerg** [comment]
By the way @gman-php, protocol42253 is 100% identical to protocol41743 -- the python files are identical.   protocol41743 is what we had when 3.2 came out.
