### ISSUE TITLE
NNet.Replay.Tracker.SUnitDiedEvent Baneling kills missing m_killerUnitTagIndex

### ISSUE THREAD

**Issue by breath20** [Blizzard/s2protocol#35]
When a baneling kills a unit, it does not correctly link the m_killerUnitTagRecycle, and m_killerUnitTagIndex for the unit that died, the info is just blank. It shows the unit died, but does not correctly link back. 

I have attached a sample replay where I only killed units with banelings and none of the NNet.Replay.Tracker.SUnitDiedEvent have the flags set correctly. 

[2016-06-04 - (Z)Breath VS (Z)A.I. 1 (Very Easy).zip](https://github.com/Blizzard/s2protocol/files/299167/2016-06-04.-.Z.Breath.VS.Z.A.I.1.Very.Easy.zip)

**Comment by jrepp** [comment]
This is committed to the 3.15 and will go out with the next available client patch. I'm going to close this for now. You can re-open it or a new issue if functionality is not as expected.
