### ISSUE TITLE
Open source s2protocol (+mpq parser) implementation in Java and Go

### ISSUE THREAD

**Issue by icza** [Blizzard/s2protocol#37]
Hello Everyone,

I'd like to announce that I have implemented / ported the `s2protocol` library to **Java** and **Go** languages. They are available as open-source projects on Github.

Java implementation is part of the open source [Scelight](https://github.com/icza/scelight) project (which is much more than just a replay parser, it also gives a high-level api):

**Java MPQ parser:** https://github.com/icza/scelight/tree/master/src-app-libs/hu/belicza/andras/mpq
**Java s2protocol:** https://github.com/icza/scelight/tree/master/src-app/hu/scelight/sc2/rep/s2prot

Go implementation is a standalone project for both MPQ and s2protocol implementation:

**Go MPQ parser:** https://github.com/icza/mpq
**Go s2protocol:** https://github.com/icza/s2prot

The Go implementation is fairly new and will improve over time. As of May 22, 2017, s2prot is also available as a standalone, self-contained CLI app which parses a passed replay file, and outputs data from the replay in JSON format. The standalone s2prot app can be downloaded here: https://github.com/icza/s2prot/releases

Hope this helps others. Should you have any questions regarding these libraries, I'd be happy to answer them.

Have fun coding and parsing replays. Don't forget to star / watch if you like them.

**Comment by amartin916** [comment]
Interesting, would be cooler if the Java version was not attached to scelight. Will be checking out the Go version

**Comment by icza** [comment]
I agree. The Java implementation was created when Scelight was closed source.

Although it doesn't have many dependencies to other parts of the project, and it is easily detachable from Scelight if someone wants to use it standalone.

**Comment by jrepp** [comment]
That's great! 

Are you able to automatically translate the protocol from python when our build system kicks out the new definition?

**Comment by icza** [comment]
Most parts of `s2protocol` have been rewritten and optimized for Go and Java, and basically the protocol files are the input to them.

When a new protocol file is released, I just have to import it (or a part of it) in the Go and Java ports, and basically the Go and Java implementations read and interpret the protocol files (e.g. the data structures of events). So yes, no problem adding them to my projects.

One thing I would like to note here. `s2protocol` is quite low level, and that's all right. But many data that can be extracted with it can be used only with the data that can be acquired using the SC2 map editor's "Export Balance Data" feature. Unfortunately since SC2 patch 3.9 the "Export Balance Data" does not export all the data it used to. One very important missing part is the texts (which associate human-readable name, icon etc. to constant values extracted from replays). Can you please look into it or forward this bug to the appropriate persons? Thanks.

**Comment by jrepp** [comment]
Is it the .py protocol definition that is an input to some automated code generator, or do you have to implement structures by hand?

I think it's OK for the python files to be a sort of 'contract' for this protocol. Our build system drives the Python implementation off an even higher level language called BSN. The output of BSN is C++, C# and Python type definitions - it can also emit JSON, XML and Lua apparently. So far we have no plan to open source BSN. It should be possible using jinja or something similar to do code gen off of the python object definitions.

I can't make any promises about the editor issue but I can look into it. It sounds like a reasonable request. Generally I think there is a push to make all game meta-data available via REST interfaces. These APIs can be used by community tools and our own websites and forums.

On the replay events comment. I totally agree that the events are very low level. In fact you need the code in the game (with the matching version) to go from a series of events to some valid observable state. There is good news in this area if you're trying to understand the game from replays. We announced are publicly available API that we hope to release soonish.

https://us.battle.net/forums/en/sc2/topic/20751114921

**Comment by icza** [comment]
The protocol .py files are interpreted (parsed) by my projects at runtime (on-demand, once only). The data structures in Java and Go are represented by dynamic, map-like models which can adapt to the structures laid out in protocol files (no manual or automatic code generation takes place).

Nice to hear about a general game meta-data REST API. But I still think the "Export Balance Data" functionality of the map editor is invaluable. It does not need a new feature, just one that was in it before (and most likely it's just a bug that texts are not outputted at the moment). The output file that's missing is `"enUS/S2Strings.xml"` (actually all translations are missing, but I only use the `enUS` version).

**Comment by icza** [comment]
@jrepp  Any word on getting "Export Balance Data" functionality of the map editor complete again? It's been several months and many patches released, it still doesn't export the so wanted texts. Without that, a big part of the s2protocol output is just "junk".

**Comment by jrepp** [comment]
Hey, one of our programmers took at look at this in the editor and there was a bug that was preventing the publish from working correctly. This should be in the next client patch!

Thanks for your patience on this issue.

**Comment by icza** [comment]
That's good news. Thanks for the note. I'll let you know after the next patch (the one after 3.15?) if there are any problems with it.

**Comment by jrepp** [comment]
We are planning a client patch for 3.15 for a different issue so you won't have to wait for 3.16.

**Comment by jrepp** [comment]
@icza Please try the 'Export Balance Data' in 3.15.1, let us know if this fixes your issue.

**Comment by icza** [comment]
@jrepp I've already tried, and yes, it works (it even worked with 3.15.0). Thank you very much.

**Comment by jrepp** [comment]
I'm going to close this issue. Can you add your projects as links to the bottom of the README.md and give me a PR?

Thanks!
