### ISSUE TITLE
Export json protocol files

### ISSUE THREAD

**Issue by breath20** [Blizzard/s2protocol#43]
It has come to light that it might be possible to get the version protocol files in another format other than the python version.

It would be beneficial if the protocol files where exported in json, could stick them in the new proposed layout #40 except I would change the layout to have one more folder layer stating the format they are in (json, python, xml, ext).

Having the format in json would make it easier for others to recreate the s2protocol in another language.

**Comment by jrepp** [comment]
Hey I'm putting the finishing touches on the internal auto generator. I added JSON support which is now available here: https://github.com/Blizzard/s2protocol/tree/updated-autogen

**Comment by jrepp** [comment]
Merged in #61
