### ISSUE TITLE
Be able to tell if a replay is an Arcade Game

### ISSUE THREAD

**Issue by breath20** [Blizzard/s2protocol#44]
Not sure if there is a sure fire way to tell if a replay is an arcade game, if there is would love to know. 

I somewhat lean on a few things like if the format ends up being 1v1, and there are more than 2 players I will reject it and also using a black list of things to just straight up reject based on map name. 

If there is not something that can tell me for sure if a replay is an arcade game would love to see something. arcade games cause my site a lot of problems and would prefer to just straight up reject them.

**Comment by jrepp** [comment]
When using --initdata check for the presence of the 'advanced matchmaking' flag (m_amm)

The path to the flag is:
  m_gameDescription.m_gameOptions.m_amm

Arcade games are not formed through the matchmaker.

Does this resolve the issue?

**Comment by breath20** [comment]
Here is an example of an arcade game http://sc2replaystats.com/download/4419966 looking at the m_gameDescription.m_gameOptions.m_amm its blank. 

I also checked a ladder game, and a private game, it was blank for all of them.

**Comment by jrepp** [comment]
I got a value of 'm_amm': False with that replay.

**Comment by breath20** [comment]
sorry I'm using php, which with how I was dumping it would make a false value results in blank, my point is still valid being I see the same results for private, Ladder, Arcade games. 

More Example Replays
Ladder vs AI http://sc2replaystats.com/download/4438782 
Ladder http://sc2replaystats.com/download/4438781
Private http://sc2replaystats.com/download/4438766

**Comment by jrepp** [comment]
Ok so the flag indicates if the game was made with the matchmaker.

When I test Ladder vs AI and Ladder I get m_amm: True
When I test Private (custom game correct?) I get m_amm: False

This is the expected behavior for this flag.

So I guess I'm saying you can definitely tell when something is 'not' an arcade game by using this flag.

Do you have any replays from arcade games to test with?

**Comment by breath20** [comment]
Ok so I have a bug on my side that is for sure, that value is not coming over correctly when I import into php. 

The first replay I linked was an arcade game, 
Here is a couple more that I quickly found
Multitasking Training http://sc2replaystats.com/download/4438625
Ling Bane Micro Wars http://sc2replaystats.com/download/4438463 

I get what your saying but I cant directly lean on the flag because players do upload private games which I don't want to reject. 

The client does know that someone is playing an arcade game I was just hoping that there would be a flag in the replay that would also notate that so I could instantly reject it.

**Comment by jrepp** [comment]
I did some more digging and implemented some new experimental attribute parsing code that might help you:

See this PR for more details https://github.com/Blizzard/s2protocol/pull/47

This is available on the dev branch, there is a new --attributeparse option, the data is still pretty rough as it's being automatically generated from data that's very implementation specific to C++ and game mods.

You will probably want to pay special attention to scope 16 which is the game scope, a container that holds attributes used to control overall game settings and logic.

Here's are the attributes from your custom game:
{
    "lobby_delay": "10",
    "rules": "Dflt",
    "game_speed": "Fasr",
    "locked_alliances": "yes",
    "parties_premade": "1v1",
    "parties_private": "t2",
    "game_mode": "Priv",
    "scope": 16,
    "privacy_option": "Norm",
    "game_duration": "0",
    "is_premade_game": "yes"
}

Here is the ladder game:

{
    "lobby_delay": "10",
    "rules": "Dflt",
    "game_speed": "Fasr",
    "locked_alliances": "yes",
    "parties_premade": "1v1",
    "parties_private": "t2",
    "game_mode": "Amm",
    "scope": 16,
    "privacy_option": "Norm",
    "game_duration": "0",
    "is_premade_game": "yes"
}

Here is ling bane micro wars:
{
    "lobby_delay": "10",
    "rules": "Dflt",
    "game_speed": "Fasr",
    "locked_alliances": "yes",
    "parties_premade": "1v1",
    "parties_private": "Cust",
    "game_mode": "Priv",
    "scope": 16,
    "privacy_option": "Norm",
    "game_duration": "0",
    "is_premade_game": "no"
}

Here's multitasking:
{
    "lobby_delay": "10",
    "rules": "Dflt",
    "game_speed": "Fasr",
    "locked_alliances": "yes",
    "parties_premade": "1v1",
    "parties_private": "t2",
    "game_mode": "Pub",
    "scope": 16,
    "privacy_option": "Norm",
    "game_duration": "0",
    "is_premade_game": "no"
}

**Comment by jrepp** [comment]
I would like to close this issue now if the original problem is being addressed by this new feature.

**Comment by amartin916** [comment]
So I actually do process the attributes currently like you are (not in as much detail) the is_premade_game might be the answer, but I have not had enough time to validate a bunch of replays before I'm willing to call it as what I need. 

Give me 48 hours and I will get back to you on it.

**Comment by jrepp** [comment]
Ok, not a huge rush! I'm at IEM in Poland and have a bit of downtime so I'm trying to close some issues ;)

Thanks again for you help 👍

**Comment by amartin916** [comment]
If you tell me no rush, the next thing you know 48 hours turns in 2 months :( Sorry for not getting back sooner been crazy busy, 

So I'm 99% sure that between is_premade_game, game_mode, and parties_private I can kick out arcade games. I'm going to add some more logging into my system before I make the change to hard kick them out, 

I will close this issue, and if I happen to find out that its not good enough will reopen it.

**Comment by jrepp** [comment]
That's ok, thank you for getting back to this :)
