### ISSUE TITLE
Adding MMR and Tier to Replay File

### ISSUE THREAD

**Issue by amartin916** [Blizzard/s2protocol#45]
Currently the MMR and Tier is not stored in the replay file. You can get it from the API, but for back processing replays it would be nice to have this information.

**Comment by jrepp** [comment]
I exposed the replay.gamemetadata.json file to the tool, you can dump this data with --metadata --json or --ndjson

This is currently only available on the 'dev' branch but will work with replays from the last few versions of the game.

Tiers will need to be queried from the web API currently.

We could see what other data could go in this file but I'm not sure how stable we want to consider the format of this yet. 

Feedback welcome.

**Comment by breath20** [comment]
Looks great, until we merge the dev branch into master (and I spend a lot of time changing over my code to be able to work with the new format) I will just take and add the metadata section into my current version. 

On the format, I would also suggest adding team, that would be useful other than that the format looks good.

**Comment by jrepp** [comment]
I've got another feature I've added on dev which is --attributeparse

You might take a look at that as another way of getting at some of the game specific data including team assignments.
