### ISSUE TITLE
Tie interceptors to the carrier that built them

### ISSUE THREAD

**Issue by amartin916** [Blizzard/s2protocol#51]
I'm not sure the best way to connect interceptors to the carrier that produced them in the replay file. Any suggestions would be appreciated. 

If there is no good way, can we add a way ?

**Comment by jrepp** [comment]
I experimented tonight with a change to add m_creatorUnitTagIndex/Recycle to the NNet.Replay.Tracker.SUnitBornEvent. Seems to be viable.

For interceptors and probably other ammo spawned units this allows figuring out which unit created it as long as you know the unit tag for the original unit which will always appear earlier in the tracker stream.

Do you think this would address this issue?

**Comment by amartin916** [comment]
Yes having it on the born event would be perfect.

Would this creatorUnitTagIndex also work for abilities that spawn units, the first one that comes to mind is the raven ? 

I was able to generate a hack on my side to "guess" the carrier but if it was in the replay file that would increase my accuracy. 

Have you seen the baneling ticket ?

**Comment by jrepp** [comment]
Ok I'll test this out on Ravens as well. I'm assuming you mean turrets and PDD?

I looked at the baneling ticket again and I'll see about getting a fix for that as well.

**Comment by amartin916** [comment]
Correct, was thinking about turrets since they spawn a unit that is timed and dies.

The key units that come to mind quickly 
Swarmhosts
Broodlords (not sure if they are a problem off hand)
carriers 
ravens

**Comment by jrepp** [comment]
This is committed to the 3.15 and will go out with the next available client patch. I'm going to close this for now. You can re-open it or a new issue if functionality is not as expected.
