### ISSUE TITLE
Missing Protocol 58400 for Patch 3.19

### ISSUE THREAD

**Issue by amartin916** [Blizzard/s2protocol#57]
Does not look like the automated job for uploading them ran this patch. 3.19 is live on the NA servers.

**Comment by jrepp** [comment]
Hi! We are in the middle of switching to a new automated process which is why we disabled the previous automated update. I will put up the new protocol tonight PST and also push the updated package to pypi.

**Comment by amartin916** [comment]
Had a feeling it was disabled since the last time it uploaded the protocol files it put them all in the wrong location :) 

Will look forward to the new file tonight, using the previous version "seems" to be working for now.

**Comment by jrepp** [comment]
Updated and uploaded to pypi with the new version scheme :)

https://pypi.python.org/pypi/s2protocol/3.19.0.58400.0
