### ISSUE TITLE
SyntaxError: invalid syntax in s2_cli.py

### ISSUE THREAD

**Issue by Necdilzor** [Blizzard/s2protocol#83]
Hello,

I'm using Python 3.6.7 and just installed s2protocol via "pip install s2protocol". After reading the tutorial [here](https://github.com/Blizzard/s2protocol/blob/master/docs/tutorial.rst#using-s2protocol-command-line-tool) I tried executing s2_cli.py but I get this syntax error in line 299.

**Comment by Necdilzor** [comment]
"except Exception, e:" causes the syntax error, maybe this is using Python 2.x? In that case, I couldn't find that mentioned in this repo.

**Comment by amartin916** [comment]
I use this with Python 2.X

**Comment by wroersma** [comment]
#89 fixes this issue. Feel free to install from https://github.com/wroersma/s2protocol/tree/cli until it's merged and test it out!

**Comment by jrepp** [comment]
Try the python 3 support in master now
