### ISSUE TITLE
unsupported base build: 71061

### ISSUE THREAD

**Issue by ipax77** [Blizzard/s2protocol#84]
After the SC2 patch from 2018/12/19  I get this error while analyzing replays from the custom map Direct Strike with s2_cli.py from version 4.8.0.71061.1:

Unsupported base build: 71061 (No module named protocol71061)

with an empty file as result. Is there any hope this will be fixed?
Thank you!

**Comment by amartin916** [comment]
Pull the most recent version of the code from the repo, you are missing /s2protocol/versions/protocol71061.py from your code base. 

That will solve your problem!

**Comment by ipax77** [comment]
That worked - ty! (I thought pip install s2protocol --upgrade is enough)
