### ISSUE TITLE
No module named attributes

### ISSUE THREAD

**Issue by mogadanez** [Blizzard/s2protocol#88]
Install  with pip and get error

```
import attributes as _attr
ImportError: No module named attributes
```
pip install attributes failed - is it standard module?

**Comment by wroersma** [comment]
https://github.com/Blizzard/s2protocol/pull/89 fixes this issue. Feel free to install from https://github.com/wroersma/s2protocol/tree/cli until it's merged and test it out!

**Comment by jrepp** [comment]
Should be fixed in master as well now
